name: BedWars
version: 1.0
api: 3.0.0, 3.0.0-ALPHA5, 3.0.0-ALPHA6
main: BedWars\BedWars
author: CreeperFace
description: BedWars plugin
depend: [MTCore]

commands:
    bw:
        description: "main bedwars command"
    blue:
        description: "join to blue team"
    red:
        description: "join to red team"
    yellow:
        description: "join to yellow team"
    green:
        description: "join to green team"
    lobby:
        description: "send to main lobby"
    stats:
        description: "show your game stats"
    vote:
        description: "vote command"