#     _    _ _ ____  _
#    / \  | | / ___|(_) __ _ _ __  ___
#   / _ \ | | \___ \| |/ _` | '_ \/ __|
#  / ___ \| | |___) | | (_| | | | \__ \
# /_/   \_\_|_|____/|_|\__, |_| |_|___/
#                      |___/
# (C) 2017 by surva network | https://github.com/survanetwork

# Language of the plugin messages
# Possible options are: en (English), de (German)
language: "en"

# Text on the sign to create a world sign (identifier) and which is displayed when it's created (text)
world:
  identifier: "world"
  text: "§9World"

# Text on the sign to create a command sign (identifier) and which is displayed when it's created (text)
command:
  identifier: "command"
  text: "§aCommand"