#
#   ___        _               _  _         _
#  / __|  _ __| |_ ___ _ __   | || |_  _ __| |
# | (_| || (_-<  _/ _ \ '  \  | __ | || / _` |
#  \___\_,_/__/\__\___/_|_|_| |_||_|\_,_\__,_|
#

#Text you will see on the server, {tps}, {load}, {players}, {max_players}, {line}, {x} {y} {z}, {coins}, {MOTD}, {faction}, {name}, {time}, {kills}, {deaths}, {ping} and & for color
#{coins} You need to use EconomyAPI to show money!
#{kills} and {deaths} You need to use KillChat to show Kill and Deaths!

#Text to show on the server in the custom bar!
text: "&7[&6Zythron&bPE&7]{line}&aHey, &e{name}!{line}&7[&6Coins&7]: &3{coins}{line}&7[&aClan&7]: &c{faction}{line}&6{x} {y} {z}"

#Time that the message is updated, P.S Leave the default 5!
time: 5

#imeZones configuration, link: https://www.timeanddate.com/time/zones , Default timezone Central European!
timezone: CET

#TimeZones Format Configuration Example (H:i) Format 24 hours (h:i A) Format 12 hours, Default formatime 24 hours!
formatime: H:i
