name: NaviCompass
author: Xenophilicy
version: 2.0.2
main: Xenophilicy\NaviCompass\NaviCompass
api: 3.0.0
Description: View all your servers or worlds in a list using FormAPI!
commands:
  servers:
    description: Transfer to available servers/worlds
