name: SimonSay
author: SimonSayTeam
main: SimonSayTeam\SimonSay\Main
version: 1.0.0
api: 1.13.0
description: Official SimonSays plugin from the NetherKingdomTeam Updates comming soon!This Plugin is in Dev!!!
