<?php

namespace Adrenaline\Commands;

use Adrenaline\CoreLoader;
use pocketmine\command\CommandSender;

class EmailCommand extends BaseCommand{
    public function __construct(CoreLoader $plugin)
    {
        parent::__construct($plugin, "email", "Set your email!", "/email [email]", []);
    }

    public function execute(CommandSender $sender, $commandLabel, array $args){
        return parent::execute($sender, $commandLabel, $args); // TODO: Change the autogenerated stub
    }
}