###Скачано с https://vk.com/mpe_plagins###

# Сколько секунд нельзя писать команды и выходить из игры после вступления в пвп режим (в секундах)

interval: 10

# Команды которое нельзя писать после вступление в пвп режим

blocked-commands:
    - /spawn
    - /home
    - /tpa
    - /call
    - /hm
    - /sp
    - /tp
    - /kill
    - /gm 
    - /tell
    - /utp
    - /sethome
    - /ugive
    - /gamemode 
    - /fly
    - /god
    - /gma
    - /gmc

###УДАЧИ В ИСПОЛЬЗОВАНИЕ ПЛАГИНА!###