package Annihilation.Arena.Object;

import cn.nukkit.item.Item;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public interface BlockList {

    List<Integer> all = new ArrayList<>();
    List<Integer> metadatable = new ArrayList<>(Arrays.asList(
            Item.WOOD,
            Item.WOOD2,
            Item.FIRE,
            Item.LEAVES,
            Item.LEAVES2,
            Item.SAPLING,
            Item.WATER,
            Item.LAVA,
            Item.SAND,
            Item.FARMLAND,
            Item.WHEAT_SEEDS,
            Item.BEETROOT_BLOCK,
            Item.PUMPKIN_STEM,
            Item.MELON_STEM,
            Item.WOOL,
            Item.STAINED_CLAY,
            Item.CARPET,
            Item.TORCH,
            Item.REDSTONE_TORCH,
            Item.RAIL,
            Item.ACTIVATOR_RAIL,
            Item.DETECTOR_RAIL,
            Item.POWERED_RAIL,
            Item.LEVER,
            Item.ACACIA_DOOR_BLOCK,
            Item.SPRUCE_DOOR_BLOCK,
            Item.DOOR_BLOCK,
            Item.JUNGLE_DOOR_BLOCK,
            Item.DARK_OAK_DOOR_BLOCK,
            Item.BIRCH_DOOR_BLOCK,
            Item.IRON_DOOR_BLOCK,
            Item.ACACIA_WOOD_STAIRS,
            Item.BIRCH_WOOD_STAIRS,
            Item.BRICK_STAIRS,
            Item.COBBLE_STAIRS,
            Item.DARK_OAK_WOOD_STAIRS,
            Item.JUNGLE_WOOD_STAIRS,
            Item.OAK_WOOD_STAIRS,
            Item.WOODEN_STAIRS,
            Item.QUARTZ_STAIRS,
            Item.STONE_BRICK_STAIRS,
            Item.SPRUCE_WOOD_STAIRS,
            Item.SANDSTONE_STAIRS,
            Item.STONE_BUTTON,
            Item.WOODEN_BUTTON,
            Item.SIGN_POST,
            Item.WALL_SIGN,
            Item.LADDER,
            Item.CHEST,
            Item.FURNACE,
            Item.DISPENSER,
            Item.JACK_O_LANTERN,
            Item.HEAVY_WEIGHTED_PRESSURE_PLATE,
            Item.LIGHT_WEIGHTED_PRESSURE_PLATE,
            Item.STONE_PRESSURE_PLATE,
            Item.WOODEN_PRESSURE_PLATE,
            Item.CAKE_BLOCK,
            Item.SLABS,
            Item.WOODEN_SLAB,
            Item.SNOW_LAYER,
            Item.BED_BLOCK,
            Item.REDSTONE_DUST,
            Item.REPEATER,
            Item.POWERED_COMPARATOR,
            Item.UNPOWERED_COMPARATOR,
            Item.DAYLIGHT_DETECTOR,
            Item.DAYLIGHT_DETECTOR_INVERTED,
            Item.GRASS,
            Item.FLOWER,
            Item.TALL_GRASS,
            Item.WATER_LILY,
            Item.TRAPDOOR,
            Item.IRON_TRAPDOOR,
            Item.DOUBLE_PLANT,
            Item.STONE_BRICK,
            Item.BROWN_MUSHROOM_BLOCK,
            Item.RED_MUSHROOM_BLOCK,
            Item.VINE,
            Item.FENCE,
            Item.FENCE_GATE_ACACIA,
            Item.FENCE_GATE_BIRCH,
            Item.FENCE_GATE_DARK_OAK,
            Item.FENCE_GATE,
            Item.FENCE_GATE_JUNGLE,
            Item.FENCE_GATE_SPRUCE,
            Item.NETHER_BRICK_FENCE,
            Item.BREWING_STAND_BLOCK,
            Item.CAULDRON_BLOCK,
            Item.COBBLESTONE_WALL,
            Item.FLOWER_POT_BLOCK,
            Item.SKULL_BLOCK,
            Item.ANVIL,
            Item.PLANKS,
            Item.QUARTZ_BLOCK,
            Item.NETHER_BRICKS_STAIRS,
            Item.DIRT,
            Item.WHEAT_BLOCK,
            Item.SUGARCANE_BLOCK,
            Item.HAY_BALE,
            Item.DOUBLE_SLAB,
            Item.DOUBLE_WOODEN_SLAB,
            Item.STILL_WATER,
            Item.STILL_LAVA,
            Item.STONE,
            Item.NETHER_PORTAL,
            Item.SANDSTONE,
            127, //COCOA
            Item.BURNING_FURNACE,
            Item.END_PORTAL_FRAME,
            Item.TRAPPED_CHEST,
            Item.CACTUS,
            132, //TRIP WIRE
            33, //piston
            34, //piston head
            Item.HOPPER_BLOCK,
            125, //DROPPER
            Item.PUMPKIN
            //Item.,
            ));
}
