---
give: '§7(§eДеньги§7) §bВы дали себе §c {count} §bденег.'
wait: '§7(§eДеньги§7) §bВы не недавно выдавали себе деньги. Подождите пожалуйста еще§c {time} §bсекунд!'
over: '§7(§eДеньги§7) §bВы можете выдавать себе максимум§c {count} §bденег!'
usage: '§eИспользование §c: §f/setmoney §a(§fколичество деньги§a)'

# Лимиты
# Писать с маленькой буквы
limit:
  Оператор:
    max: 20000
    time: 15 # в минутах
  Основатель: 
    max: 35000
    time: 15
  Владелец: 
    max: 50000
    time: 15
  Админ: 
    max: 10000
    time: 15
...