---

# Шанс на рождение ребенка (по стандарту 1-5)
# Что бы убрать шанс (поставьте false)
ChildChance: 5

# Цена за занятие сексом (по стандарту 5000$)
# Что бы сделать бесплатным (поставьте false)
PriceSex: 5000

# Цена за то что сам себе подрочил (по стандарту 1000$)
# Что бы сделать бесплатным (поставьте false)
PriceMasturbation: 1000

# Включить ли ведро спермы? (true - включить, false - отключить)
BucketSperm: true
# Игрок выпьет ведро спермы, и возможно забеременеет, укажите шанс (по стандарту 1-5)
# Что бы убрать шанс (поставьте false)
SpermChance: 5

...