---
# AutoClearLagg (ACL) Settings

# Seconds between each clear lagg
seconds: 300

# Things to clear
items: true
mobs: true

# Messages broadcasted
all-cleared-message: §cAll entites cleared
items-cleared-message: §cAll items cleared
mobs-cleared-message: §cAll mobs cleared
...
