# MultiProtocol by FaigerSYS (vk.com/alex_2534)

# Поддерживаемые протоколы
protocols:
  - 100
  - 101

# Известные протоколы (начиная с MCPE 1.0):
#   100 - MCPE 1.0
#   101 - MCPE 1.0.3

# Внимание! Протоколы меняются не просто так, а из-за изменений в них.
# Возможности нового протокола могут быть недоступны в старом. Пример:
#   В протоколе версии 101 добавии возможность трансфера между серверами, но в игроков с версией протокола 100 эта возможность не будет доступна

# Узнать действующий протокол ядра можно по команде "/currectprotocol"
