---
##############################
# Donate  by Dragonfive (vk.com/onebot)
# Your using version 0.0.1
##############################


#add you donate list
donate1: "§5Fly - 10 рублей"
donate2: "§6Vip - 25 рублей"
donate3: "§9Creativ - 50 рублей"
donate4: "§a Moderator - 70 рублей"
donate5: "§cАдминистратор - 100 рублей"
donate6: "§4You§ftube - 500 подписчиков"
donate7: "§lOP - 200 рублей"
donate8: "§6Приглашайте друзей!"
donate9: "§9И получите скидку!"
donate10: "§4 покупать у §aMrGyner!"
#Max 10 line!
#Please not add line!
#Delete line can't
...