---
MaxAreas: 5
MaxAreaSize: 25000
DefaultFlags:
  pvp: deny
  build: deny
  entry: allow
  god-mode: deny
  use: deny
  cmd-use: allow
  send-chat: allow
  explode: allow
  burn: allow
  regain: allow
  teleport: allow
  mob-damage: allow
  sleep: allow
  tnt-explode: deny
  bucket-use: deny
  drop-item: allow
...
