name: OWGuard
main: ow\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorMain
version: ultra
api: 2.0.0
author: BlackJIeB
load: POSTWORLD
description:
commands:
 owguard:
  description: "Приват территорий"
  permission: rg.p
permissions:
 rg:
  description: Top permissions of PrivateRegionProtector
  default: op
  children:
   rg.p:
    descrition: "Allow to protect areas"
    default: true
   rg.breakall:
    descrition: "Allow to change all areas"
    default: op
   rg.maxsize:
    default: op
    description: "Allow to create area with any size"
   rg.doall:
    default: op
    description: "Allow to do all"
   rg.maxareas:
    default: op
    description: "Allow to create areas bigger default"
   rg.flag:
    default: true
    description: "Allow to use flags"
   flag.pvp:
    default: true
    descriprion: "Allow to use flag pvp"
   flag.use:
    default: true
    descriprion: "Allow to use flag use"
   flag.entry:
    default: op
    descriprion: "Allow to use flag entry"
  flag.send-chat:
    default: op
    descriprion: "Allow to use flag send-chat"
  flag.explode:
    default: op
    descriprion: "Allow to use flag explode"
  flag.burn:
    default: op
    descriprion: "Allow to use flag burn"
  flag.build:
    default: op
    descriprion: "Allow to use flag build"
  flag.sleep:
    default: op
    descriprion: "Allow to use flag sleep"
  flag.mob-damage:
    default: op
    descriprion: "Allow to use flag mob-damage"
  flag.tnt-explode:
    default: op
    descriprion: "Allow to use flag tnt-explode"
  flag.drop-item:
   default: op
   description: "Allow to use flag drop-item"