# ____                   _ _   _                    _
#|  _ \ ___   __ _  __ _(_) |_| |    ___   __ _  __| | ___ _ __
#| |_) / _ \ / _` |/ _` | | __| |   / _ \ / _` |/ _` |/ _ \ '__|
#|  __/ (_) | (_| | (_| | | |_| |__| (_) | (_| | (_| |  __/ |
#|_|   \___/ \__, |\__, |_|\__|_____\___/ \__,_|\__,_|\___|_|
#            |___/ |___/
# (C) 2017 by surva network | https://github.com/survanetwork

# Check if the server's API version is compatible with the plugin's one
#
# Possible values are:  1 (check the API version and don't install if not compatible)
#                       2 (install all plugins but show a warning if the API version is not compatible)
#                       3 (install all plugins without any warning)
api: 1

# Installed plugins, don't change manually
installed: