---
join_message: true #Включение/выключение сообщения при входе на сервер
join_particle: true #Включение/выключение фейерверков при входе на сервер
join_message_text: "До Нового Года осталось {TN}, а до Рождества {TC}." #Текст сообщения при входе на сервер {TN} - дата до нового года, {TC} дата до рождества

santa_claus: "Игрока {player} навестил добрый дед мороз и принес ему подарочек." #Текст сообщения когда игрока навестил добрый дед мороз
interval: 1 #Интервал в минутах когда дед мороз ходит по игрокам
items: #массив с предметами для выдачи
- "295:0:1"

float: true #Включение/выключение летающего сообщения
float_x: 115
float_y: 74
float_z: 156
float_text: "С наступающим" #Текст летающего сообщения
...
