name: BlazinBroadcasts
version: 1.0.3
main: iiFlamiinBlaze\BlazinBroadcasts\BlazinBroadcasts
api: 3.0.0
description: An advanced auto broadcasting plugin for PocketMine
author: iiFlamiinBlaze
commands:
 blazinbroadcasts:
  description: BlazinBoradcasts config management command
  permission: blazinbroadcasts.command
permissions:
 blazinbroadcasts.command:
  default: op