---
##############################
# Donate  by Dragonfive (vk.com/onebot)
# Your using version 0.0.1
##############################


#add you donate list
donate1: "1 Donate"
donate2: "2 Donate"
donate3: "3 Donate"
donate4: "4 Donate"
donate5: "5 Donate"
donate6: "6 Donate"
donate7: "7 Donate"
donate8: "8 Donate"
donate9: "9 Donate"
donate10: "10 Donate"
#Max 10 line!
#Please not add line!
#Delete line can't
...