#name, main, version and api are required
name: MCG76_WorldEdit
main: mcg76\plugin\worldedit\WorldEditPlugIn
version: 0.5.2
api: 1.8.0
author: minecraftgenius76
description: mcg76 MCPE WorldEditor 
commands:
 /:
  description: "minecraftgenius76 WorldEditor"
  permission: mcg76.plugin.worldeditor
permissions:
 mcg76.plugin.worldeditor:
  description: "mcg76.plugin.worldeditor"
  default: op