---

#	Разрешить ли пользоваться зачарованием и починкой предмета игрокам в креативе?
#	false - нет. true - да. Рекомендуем оставить false.
allow-creative: false

#	Сообщение, если игрок пытается зачаровать / починить предмет в креативе и если параметр allow-creative = true.
message-no-creative: "§6> §eНеобходимо быть в режиме выживания!"

#	Сообщение, если в руке не инструмент или броня.
message-only-tools: "§6> §eУ Вас в руке должен быть инструмент или броня!"


#	Какой предмет принимать в качестве оплаты за ЗАЧАРОВАНИЕ?
#	По-умолчанию стоит Лазурит.
item-id-enchant: 351
item-damage-enchant: 4
#	Сколько предметов забирать за одно ЗАЧАРОВАНИЕ, если у игрока нет пермишена free.enchant
item-count-enchant: 10
#	Уровень зачарования предмета:
#	Если установлен 0, то предмет будет зачарован на рандомный уровень от 1 до 3.
level-enchant: 0

#	Сообщение, если не хватает предметов.
message-no-items-enchant: "§6> §eДля зачарования Вам надо§6 10 лазурита."
#	Сообщение при успешном зачаровании.
message-enchant: "§6> §eПредмет в руке был успешно зачарован!"


#	Какой предмет принимать в качестве оплаты за ПОЧИНКУ?
#	По-умолчанию стоит Железо.
item-id-repair: 265
item-damage-repair: 0
#	Сколько предметов забирать за одну ПОЧИНКУ, если у игрока нет пермишена free.repair
item-count-repair: 5

#	Сообщение, если не хватает предметов.
message-no-items-repair: "§6> §eДля починки Вам надо§6 5 железа."
#	Сообщение при успешной починке.
message-repair: "§6> §eПредмет в руке был успешно починен!"

...