id: "0"
token: "cc255e0e1ab8fd8d7783fe219aa51ff0c7043872bab51b2a66cba04346bbdb1cef64db4c16bc47c0cb1f8"
banmessage: "               §cВаш аккаунт заблокирован.§f \n §bДля разблокировки переходите к нам в группу: §avk.com/bomba_mcpe."
