---
Координаты:
  Табличка:
    x: 371
    "y": 70
    z: 797
  Рамка:
    x: 371
    "y": 69
    z: 797
  Кнопка+:
    x: 370
    "y": 70
    z: 797
  Кнопка-:
    x: 372
    "y": 70
    z: 797
  Кнопка следующее:
    x: 370
    "y": 69
    z: 797
  Кнопка предыдущее:
    x: 372
    "y": 69
    z: 797
  Кнопка купить:
    x: 371
    "y": 68
    z: 797
Товары:
  0:
    ID: 2
    Damage: 1
    Цена: 50
  1:
    ID: 264
    Damage: 1
    Цена: 100
  2:
    ID: 261
    Damage: 1
    Цена: 150
  3:
    ID: 262 
    Damage: 1
    Цена: 50
  4:
    ID: 322
    Damage: 1
    Цена: 150
  5:
    ID: 4
    Damage: 1
    Цена: 50
  6:
    ID: 18
    Damage: 1
    Цена: 50
  7:
    ID: 89
    Damage: 1
    Цена: 100
  8:
    ID: 368
    Damage: 1
    Цена: 50
  9:
    ID: 155 
    Damage: 1
    Цена: 50
  10:
    ID: 17:2
    Damage: 1
    Цена: 20 
  11:
    ID: 17 
    Damage: 1
    Цена: 15 
  12:
    ID: 41
    Damage: 1
    Цена: 500
  13:
    ID: 42
    Damage: 1
    Цена: 500
  14:
    ID: 22
    Damage: 5
    Цена: 500
Табличка: 
  1: '§aЦена'
  2: '§6{price}'
  3: '§cКол-во'
  4: '§d{count}'
Сообщения:
  Успешно: '§aСпасибо за покупку! Ваша покупка добавлена в ваш инвентарь!'
  Ошибка: '§cУ вас недостаточно денег на счету для покупки!'
...