#                        Copyright (C) 2016 EntirelyQuartz                                                                                       
#  ,ad8888ba,    88        88         db         88888888ba   888888888888  888888888888  
# d8"'    `"8b   88        88        d88b        88      "8b       88                ,88  
#d8'        `8b  88        88       d8'`8b       88      ,8P       88              ,88"   
#88          88  88        88      d8'  `8b      88aaaaaa8P'       88            ,88"     
#88          88  88        88     d8YaaaaY8b     88""""88'         88          ,88"       
#Y8,    "88,,8P  88        88    d8""""""""8b    88    `8b         88        ,88"         
# Y8a.    Y88P   Y8a.    .a8P   d8'        `8b   88     `8b        88       88"           
#  `"Y8888Y"Y8a   `"Y8888Y"'   d8'          `8b  88      `8b       88       888888888888  
#  
---
enable-teamchat: true
...