name: ShoppingCartPE
author: MamayAdesu
api: 1.2.0
version: "1.1"
main: mamayadesu\scp\scp

commands:
 cart:
  permission: cart
  usage: /cart get <purchase_id | all>
 
permissions:
 cart:
  default: true
  description: Allows to use ShoppingCartPE
