---
give: '§7(§eДеньги§7) §bВы дали себе §c {count} §bденег.'
wait: '§7(§eДеньги§7) §bВы не недавно выдавали себе деньги. Подождите пожалуйста еще§c {time} §bсекунд!'
over: '§7(§eДеньги§7) §bВы можете выдавать себе максимум§c {count} §bденег!'
usage: '§eИспользование §c: §f/setmoney §a(§fколичество деньги§a)'

# Лимиты
# Писать с маленькой буквы
limit:
  Admin:
    max: 10000
    time: 5 # в минутах
  Gospodin: 
    max: 20000
    time: 3
  Sozdatel: 
    max: 30000
    time: 2
...