#ВНИМАНИЕ!!! слова вроде "[name], [money]" и тд НЕ ТРОГАТЬ!!!
# Автор плагина Ян Петров. http://vk.com/id275047978
main: §7За убийство игрока §b[name] §cдается вознаграждение размером в §a[money] монет
errornumber: §eЦена должна быть больше нуля §a/ в поле цены надо вводить число
errormoney: §7Тебе нехватает денег
errorset: §7За игрока уже обьявили §aвознаграждение
notonline: §6Игрок [player] не онлайн
killer: §cМолодец! §eты убил игрока по заказу!
usage: §aИспользовование §7/zakaz <игрок> <цена>
zakazok: §eВы успешно сделали заказ на убийство игрока
playerback: §aЗаказанный игрок §b[name] §aвернулся в игру! \n §cОн не знает что за ним охотятся!