---
# Если вдруг у тебя нет, то возьми -> §

# заголовок списка
title: "§f[§baKits§f] §aСписок доступных наборов:"
# список наборов
kit: §b{kit}

# Набор недоступен
notAvailable: §f[§baKits§f] §cТебе недоступен этот набор!

# набора не существует
notExist: §f[§baKits§f] §cТакого набора не существует!

# набор выдан
give: §f[§baKits§f] §3Тебе выдан набор §a{kit}§3. Следующий сможешь взять через {time} секунд

# уже выдан, надо подождать
wait: §f[§baKits§f] §eТы уже брал этот набор, подожди еще {time} секунд

...