name: ZA
main: RogVaLoT\Main
version: Final
author: YanPetrov
api: [1.12.0] 
load: POSTWORLD
commands:
 zakaz:
  permission: command.zakaz
  default: true
permissoins:
  command.zakaz:
  default: true